"""spec-runner config — apply CLI profile presets to spec-runner.config.yaml."""

from __future__ import annotations

import argparse
import shutil
import sys
from dataclasses import dataclass
from importlib.resources import files
from pathlib import Path
from typing import TYPE_CHECKING

import yaml

if TYPE_CHECKING:
    from .config import ExecutorConfig

CONFIG_FILE = Path("spec-runner.config.yaml")
LEGACY_CONFIG_FILE = Path("spec/executor.config.yaml")

# CLI names: the first six are auto-detected by runner.build_cli_invocation;
# qwen and copilot are template-driven (not auto-detected).
PRESET_NAMES = [
    "claude",
    "codex",
    "opencode",
    "pi",
    "ollama",
    "llama-cli",
    "qwen",
    "copilot",
]

# The 7 CLI-profile keys the composer manages (top-level executor-mapping keys).
PROFILE_KEYS = [
    "claude_command",
    "claude_model",
    "command_template",
    "skip_permissions",
    "review_command",
    "review_model",
    "review_command_template",
]


@dataclass(frozen=True)
class Fragment:
    """Slot-neutral description of how to invoke one CLI."""

    command: str
    model: str = ""
    skip_permissions: bool = False
    exec_template: str = ""
    review_template: str = ""
    model_flag: str = ""
    note: str = ""


def list_presets() -> list[str]:
    """Return the available preset names."""
    return list(PRESET_NAMES)


def load_fragment(name: str) -> Fragment:
    """Load a preset fragment by CLI name from bundled package data."""
    if name not in PRESET_NAMES:
        valid = ", ".join(PRESET_NAMES)
        raise ValueError(f"Unknown preset '{name}'. Valid presets: {valid}")
    resource = files("spec_runner") / "presets" / f"{name}.yaml"
    data = yaml.safe_load(resource.read_text()) or {}
    if "command" not in data:
        raise ValueError(f"Preset file for '{name}' is missing required 'command' key")
    return Fragment(
        command=data["command"],
        model=data.get("model", ""),
        skip_permissions=bool(data.get("skip_permissions", False)),
        exec_template=data.get("exec_template", ""),
        review_template=data.get("review_template", ""),
        model_flag=data.get("model_flag", ""),
        note=data.get("note", ""),
    )


def _apply_model_flag(template: str, model_flag: str, model: str) -> str:
    """Append the model flag to a template only when there is a template, a flag,
    and a non-empty model — avoids a dangling `--model` with no value."""
    if template and model_flag and model:
        return f"{template} {model_flag} {{model}}"
    return template


def compose(
    exec_frag: Fragment,
    review_frag: Fragment,
    model_override: str = "",
    review_model_override: str = "",
) -> dict[str, object]:
    """Map an (exec, review) fragment pair into the 7 CLI-profile keys.

    `command_template` comes from the exec fragment, `review_command_template`
    from the review fragment. Auto-detect CLIs carry empty templates, which also
    clears any stale template from a previously configured CLI. Model precedence:
    per-slot override > shared --model override > fragment default.

    When a fragment has a `model_flag` (e.g. ``"--model"``), it is appended to
    the template only when the resolved model is non-empty — avoiding a dangling
    ``--model`` argument when no model is supplied.
    """
    exec_model = model_override or exec_frag.model
    review_model = review_model_override or model_override or review_frag.model
    return {
        "claude_command": exec_frag.command,
        "claude_model": exec_model,
        "command_template": _apply_model_flag(
            exec_frag.exec_template, exec_frag.model_flag, exec_model
        ),
        "skip_permissions": exec_frag.skip_permissions,
        "review_command": review_frag.command,
        "review_model": review_model,
        "review_command_template": _apply_model_flag(
            review_frag.review_template, review_frag.model_flag, review_model
        ),
    }


_FRESH_HEADER = """\
# spec-runner configuration (v2.0 flat format)
# Generated by `spec-runner config`. Edit freely.

# --- CLI profile (managed by `spec-runner config`) ---
"""

_FRESH_SCAFFOLD = """\

# --- Common knobs (uncomment to use) ---
# budget_usd: 10.0
# task_budget_usd: 2.0
# max_concurrent: 3
# telegram_bot_token: ""      # secret — keep out of version control
# telegram_chat_id: ""
# webhook_url: ""
"""


def _fmt_scalar(value: object) -> str:
    """Render a profile value as a YAML scalar for the static fresh template."""
    if isinstance(value, bool):
        return "true" if value else "false"
    return '""' if value == "" else f'"{value}"'


def _render_fresh(profile: dict[str, object]) -> str:
    """Build a flat v2.0 config file as static text (preserves comments)."""
    lines = "\n".join(f"{k}: {_fmt_scalar(profile[k])}" for k in PROFILE_KEYS)
    return _FRESH_HEADER + lines + "\n" + _FRESH_SCAFFOLD


def apply_to_config(
    profile: dict[str, object],
    *,
    apply_changes: bool,
    dry_run: bool,
    config_path: Path = CONFIG_FILE,
) -> Path | None:
    """Write a fresh config, preview (dry-run), refuse, or surgically merge.

    Returns the written path, or None for a dry-run.
    """
    target_path = config_path
    if not target_path.exists() and LEGACY_CONFIG_FILE.exists():
        target_path = LEGACY_CONFIG_FILE

    # dry_run short-circuits before any file check (applies in all cases)
    if dry_run:
        _print_profile(profile)
        return None

    if not target_path.exists():
        config_path.write_text(_render_fresh(profile))
        return config_path

    if not apply_changes:
        _print_profile(profile)
        print(
            f"{target_path} exists. Re-run with --apply to update the CLI "
            "profile (other settings preserved), or --dry-run to preview.",
            file=sys.stderr,
        )
        raise SystemExit(1)

    return _merge_into_existing(profile, target_path)


def _print_profile(profile: dict[str, object]) -> None:
    """Print the 7 keys that would be written (stdout), in YAML scalar format."""
    for key in PROFILE_KEYS:
        print(f"{key}: {_fmt_scalar(profile[key])}")


def _merge_into_existing(profile: dict[str, object], target_path: Path) -> Path:
    """Overwrite only the 7 CLI-profile keys, preserving shape and other keys."""
    raw = target_path.read_text()
    try:
        existing = yaml.safe_load(raw)
    except yaml.YAMLError as exc:
        print(f"{target_path}: cannot parse YAML: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc
    if existing is None:
        existing = {}
    if not isinstance(existing, dict):
        print(f"{target_path}: expected a top-level YAML mapping", file=sys.stderr)
        raise SystemExit(1)

    # Select target mapping; mirror load_config_from_yaml's flat/wrapped rule.
    target: dict[str, object] = existing.get("executor", existing)
    if not isinstance(target, dict):
        print(f"{target_path}: 'executor' is not a mapping", file=sys.stderr)
        raise SystemExit(1)

    backup = target_path.parent / (target_path.name + ".bak")
    shutil.copyfile(target_path, backup)
    target.update(profile)
    target_path.write_text(yaml.safe_dump(existing, sort_keys=False, allow_unicode=True))
    return target_path


def cmd_config(args: argparse.Namespace, config: ExecutorConfig | None = None) -> None:
    """CLI entry for `spec-runner config`."""
    if args.list_presets:
        for name in list_presets():
            print(name)
        return

    exec_name: str = args.exec_cli or args.preset or ""
    review_name: str = args.review_cli or args.preset or ""
    if not exec_name or not review_name:
        print(
            "Specify --preset X (mono) or --exec X --review Y (multi). See --list-presets.",
            file=sys.stderr,
        )
        sys.exit(2)

    try:
        exec_frag = load_fragment(exec_name)
        review_frag = load_fragment(review_name)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        sys.exit(2)

    profile = compose(
        exec_frag,
        review_frag,
        model_override=args.model or "",
        review_model_override=args.review_model or "",
    )
    written = apply_to_config(
        profile,
        apply_changes=args.apply,
        dry_run=args.dry_run,
    )
    if written is not None:
        for note in dict.fromkeys(n for n in (exec_frag.note, review_frag.note) if n):
            print(f"note: {note}")
        print(f"Wrote {written}. Run 'spec-runner doctor' to verify the CLI profile.")
